/* parametry.h */ 


//PRZERWY CZASOWE 
#define CZAS_PAUZY_1		100

//PUSTE POLE SAP 1
#define PUSTE_POLE_SAP_1		1000, 750

//ZIELONY ZNACZEK POLA G£OWNEGO  
#define ZNACZEK_POLA_GLOWNEGO_OS_X      975
#define ZNACZEK_POLA_GLOWNEGO_OS_Y      1003

//ZMIANA SPECYFIKACJI - PRZEGL¥D POZYCJI
#define ZMIANA_SPECYFIKACJI_PRZEGLAD_POZYCJI_OS_X       1500
#define ZMIANA_SPECYFIKACJI_PRZEGLAD_POZYCJI_OS_Y       390

//ZMIANA SPECYFIKACJI - PRZYCISK USUWANIA
#define ZMIANA_SPECYFIKACJI_PRZYCISK_USUWANIA_OS_X       1150
#define ZMIANA_SPECYFIKACJI_PRZYCISK_USUWANIA_OS_Y       270

//ZMIANA SPECYFIKACJI - USUWANIE ALTERNATYWY
#define ZMIANA_SPECYFIKACJI_USUWANIE_ALTERNATYWY_OS_X       1500
#define ZMIANA_SPECYFIKACJI_USUWANIE_ALTERNATYWY_OS_Y       320

//CIEMNY SZARY
#define KOLOR_SZARY_1_RGB_1		a != 229 and b != 229 and c != 229

//ZIELONY - IKONA
#define KOLOR_ZIELONY_1_RGB_1		a != 0 and b != 139 and c != 0

//NIEBIESKI
#define KOLOR_NIEBIESKI_1_RGB_1		a != 0 and b != 157 and c != 224

//BIA£Y
#define KOLOR_BIALY_1_RGB_1		a != 255 and b != 255 and c != 255
